version: "3"

services:
  # server:
  #   build: .
  #   command:
  #   environment:
  #     - DB_NAME=arclab
  #     - DB_HOST=edgedb
  #     - DB_USER=user
  #     - DB_PASSWORD=secret
  #     - DB_PORT=5656
  #   ports:
  #     - 5000:5000
  #   depends_on:
  #     - edgedb
  edgedb:
    image: edgedb/edgedb
    environment:
      - EDGEDB_SERVER_SECURITY=insecure_dev_mode
      - EDGEDB_SERVER_DATABASE=arclab
      - EDGEDB_SERVER_PASSWORD=secret
    volumes:
      - ./dbschema:/dbschema
      - ./credentials:/root/.config/edgedb/credentials
      - edgedb_data:/var/lib/edgedb/data
    ports:
      - "5656:5656"

volumes:
  edgedb_data:
